import Foundation

enum TokenStepLocalization {
    private(set) static var selectedLanguage: TokenStepLanguage = .system

    static var language: TokenStepLanguage {
        selectedLanguage.resolved
    }

    static var locale: Locale {
        Locale(identifier: language.localeIdentifier)
    }

    static func apply(_ language: TokenStepLanguage) {
        selectedLanguage = language
    }

    static func text(_ key: String) -> String {
        guard language != .zhHans else { return key }
        return translations[language]?[key] ?? key
    }

    static func format(_ key: String, _ arguments: CVarArg...) -> String {
        format(key, arguments)
    }

    static func format(_ key: String, _ arguments: [CVarArg]) -> String {
        String(format: text(key), locale: locale, arguments: arguments)
    }

    private static let translations: [TokenStepLanguage: [String: String]] = [
        .en: [
            "自动": "Auto",
            "刘海左侧": "Left of notch",
            "刘海右侧": "Right of notch",
            "菜单栏": "Menu bar",
            "左侧": "Left",
            "右侧": "Right",
            "跟随系统": "Follow System",
            "自动匹配 macOS": "Match macOS",
            "准备更新": "Preparing update",
            "正在下载": "Downloading",
            "正在安装并重启": "Installing and relaunching",
            "更新失败": "Update failed",
            "菜单栏模式": "Menu bar mode",
            "自动：刘海旁": "Auto: beside notch",
            "自动：菜单栏": "Auto: menu bar",
            "鼠标移入后展开浮层": "Hover to expand",
            "鼠标移入后展开 Island": "Hover to expand Island",
            "仅使用右上角菜单栏入口": "Use menu bar only",
            "刷新": "Refresh",
            "打开 TokenFleet": "Open TokenFleet",
            "设置": "Settings",
            "等待同步": "Waiting to sync",
            "Token 采集超时，请稍后重试": "Token collection timed out. Please try again later.",
            "Token 重新校准未完成，已保留原统计。": "Token recalibration did not complete. The previous totals were preserved.",
            "TokenFleet 已按真实增量重新校准历史 Token。数字可能变小，但历史记录没有丢失。": "TokenFleet recalibrated historical Token usage using true increments. The number may be lower, but no history was lost.",
            "关闭": "Close",
            "手动": "Manual",
            "%d 分钟": "%d min",
            "1 分钟": "1 min",
            "第 %d 圈": "Lap %d",
            "第 %d 圈 · %@": "Lap %d · %@",
            "已完成 %d 圈": "%d laps completed",
            "已完成 %@": "%@ completed",
            "每圈目标 %@": "%@ per lap",
            "少": "Less",
            "多": "More",
            "活跃": "Active",
            "达标": "Goal",
            "最高": "Best",
            "近 8 个月活动墙": "Last 8 Months",
            "颜色越深，越接近或超过每日目标": "Darker means closer to, or beyond, the daily goal",
            "颜色越深，用量越高；描边是今天": "Darker means more usage; outline marks today",
            "%d 个活跃日": "%d active days",
            "全部明细": "All Details",
            "%d 条记录，向下滚动查看完整历史": "%d records. Scroll down for full history",
            "最近 %d 天，适合保存为截图": "Last %d days, ready for screenshots",
            "日期": "Date",
            "Token 消耗": "Token Usage",
            "消耗金额": "Cost",
            "主力工具": "Main Tool",
            "工具": "Tools",
            "%d 个模型": "%d models",
            "输入": "Input",
            "输出": "Output",
            "缓存读": "Cache Read",
            "缓存写": "Cache Write",
            "总计": "Total",
            "工具汇总": "Tool totals",
            "模型汇总": "Model totals",
            "无可用汇总": "No totals available",
            "仅总量 · 分项不完整": "Total only · incomplete breakdown",
            "旧数据仅有工具与模型的独立汇总，无法还原它们的对应关系。": "Legacy data only has separate tool and model totals; their relationship cannot be reconstructed.",
            "原子明细与当日总计不一致，本次仅展示已采集的精确明细。": "The atomic detail does not match the daily total. Only collected exact detail is shown.",
            "无": "None",
            "累计 Token 消耗": "Total Token Usage",
            "等待下一次同步": "Waiting for next sync",
            "最近 30 天": "Last 30 Days",
            "颜色越深，圈数越高": "Darker means a higher lap",
            "柱越高，用量越多；颜色代表客户端": "Taller bars mean more usage; colors show clients",
            "柱越高，用量越多": "Taller bars mean more usage",
            "颜色代表客户端": "Colors show clients",
            "今天 %@": "Today %@",
            "/ %@ 每圈": "/ %@ per lap",
            "圈数进度": "Lap Progress",
            "按客户端": "By Client",
            "按模型": "By Model",
            "今日客户端": "Today by Client",
            "今日模型": "Today by Model",
            "累计总量分布": "Total distribution",
            "主力模型": "Top Models",
            "本月均值": "Monthly Avg",
            "活跃天数": "Active Days",
            "达标天数": "Goal Days",
            "有 AI 使用的日期": "Days with AI usage",
            "达到每日目标": "Reached daily goal",
            "%d圈完成": "Lap %d done",
            "%@进行中": "%@ in progress",
            "所有本机记录": "All local records",
            "今日": "Today",
            "历史": "History",
            "统计": "Analytics",
            "模型与工具": "Models & Tools",
            "隐私": "Privacy",
            "今日消耗": "Today",
            "历史活动": "History",
            "用量统计": "Analytics",
            "今天的 Token 使用节奏": "Today’s token rhythm",
            "长期节奏和所有历史记录": "Long-term rhythm and all history",
            "按客户端和模型拆开看": "Break down by client and model",
            "只统计数量，不读取内容": "Only counts usage, never reads content",
            "保存当前页 PNG（最近 30 天）": "Save Page PNG (Last 30 Days)",
            "保存当前页 PNG": "Save Page PNG",
            "复制当前页截图": "Copy Page Screenshot",
            "截取当前页": "Capture Page",
            "更新": "Updated",
            "同步中": "Syncing",
            "已同步": "Synced",
            "每天一个亿": "100M a day",
            "本地统计": "Local Only",
            "本地统计 + 社群榜日汇总": "Local + Community Leaderboard Daily Aggregates",
            "不上传代码或对话": "No code or chats uploaded",
            "今日 AI 战绩": "Today’s AI Scorecard",
            "昨日 AI 工作成绩单": "Yesterday’s AI Scorecard",
            "今天我和 AI 一起消耗了": "Today I used with AI",
            "昨天我和 AI 一起完成了": "Yesterday I completed with AI",
            "已完成": "Completed",
            "仅供参考": "Reference only",
            "今日来源": "Today Sources",
            "昨日来源": "Yesterday Sources",
            "今日 Token": "Today Token",
            "按 Token 消耗排序": "Sorted by token usage",
            "完成度": "Completion",
            "总完成度": "Total completion",
            "这是一个新的记录日": "This is a new record day",
            "和前一天基本持平": "About the same as the previous day",
            "比前一天多 %@": "%@ more than previous day",
            "比前一天少 %@": "%@ less than previous day",
            "分享今日卡片": "Share Today Card",
            "分享昨日成绩": "Share Yesterday Recap",
            "分享昨日节奏": "Share Yesterday Rhythm",
            "下载今日卡片": "Download Today Card",
            "下载昨日成绩": "Download Yesterday Recap",
            "下载昨日节奏": "Download Yesterday Rhythm",
            "分享战绩卡片": "Share scorecard",
            "截图与分享": "Capture and Share",
            "还没有昨日数据": "No yesterday data yet",
            "昨日节奏还在等待同步": "Yesterday rhythm is waiting for sync",
            "本地 AI 使用节奏": "Local AI usage rhythm",
            "AI Token 使用追踪": "AI Token Usage Tracking",
            "昨日 AI 节奏": "Yesterday AI Rhythm",
            "完整 24h": "Full 24h",
            "24 小时波形": "24-hour waveform",
            "颜色随时段变化，最高柱是峰值": "Color follows time of day; tallest bar is the peak",
            "峰值": "Peak",
            "峰值 %@": "Peak %@",
            "活跃时段": "Active Hours",
            "%d 个时段": "%d hours",
            "昨日 Token": "Yesterday Tokens",
            "夜间占比": "Night Share",
            "最长连续": "Longest Streak",
            "%d 小时": "%d h",
            "全天总量": "Daily total",
            "昨天的完整 AI 协作节拍": "A full-day AI collaboration rhythm",
            "清晨启动型": "Early Starter",
            "上午规划型": "Morning Planner",
            "下午爆发型": "Afternoon Burst",
            "晚间冲刺型": "Evening Sprint",
            "夜间 Agent 型": "Night Agent",
            "双峰推进型": "Double Peak",
            "碎片推进型": "Fragmented Pusher",
            "一波流型": "One-Shot Sprint",
            "稳定巡航型": "Steady Cruiser",
            "低频轻触型": "Light Touch",
            "一早就把 AI 拉进工作台": "Pulled AI into the workspace early",
            "上午定方向，后面稳稳推进": "Set direction in the morning, then kept moving",
            "午后能量拉满，一段时间集中爆发": "Afternoon energy peaked in a focused burst",
            "晚间突然加速，把任务向前顶了一截": "A sudden evening sprint pushed the work forward",
            "夜里交给 Agent，把任务往前推": "Handed work to agents at night",
            "一天两次拉满，节奏很有层次": "Two strong peaks made the day layered",
            "多时段穿插推进，随手就把活干了": "Moved work forward across scattered moments",
            "集中一波解决主要战斗": "Solved the main battle in one concentrated push",
            "稳定巡航，没有明显掉线": "Cruised steadily without dropping off",
            "轻量使用，保留一点 AI 手感": "Light usage, keeping the AI habit warm",
            "投缘搭子：夜间 Agent 型": "Best rhythm mate: Night Agent",
            "投缘搭子：下午爆发型": "Best rhythm mate: Afternoon Burst",
            "投缘搭子：上午规划型": "Best rhythm mate: Morning Planner",
            "投缘搭子：清晨启动型": "Best rhythm mate: Early Starter",
            "投缘搭子：稳定巡航型": "Best rhythm mate: Steady Cruiser",
            "投缘搭子：一波流型": "Best rhythm mate: One-Shot Sprint",
            "投缘搭子：碎片推进型": "Best rhythm mate: Fragmented Pusher",
            "投缘搭子：双峰推进型": "Best rhythm mate: Double Peak",
            "你负责清晨开局，TA 负责夜里收尾。": "You open early; they close at night.",
            "你负责上午定盘，TA 负责下午冲刺。": "You set the plan; they sprint in the afternoon.",
            "你负责午后爆发，TA 负责上午定盘。": "You burst in the afternoon; they set the morning plan.",
            "你负责深夜推进，TA 负责清晨接棒。": "You push at night; they pick it up in the morning.",
            "你负责两次拉满，TA 负责稳定托底。": "You bring two peaks; they keep the baseline steady.",
            "你负责随手推进，TA 负责集中攻坚。": "You move things in pieces; they handle the focused push.",
            "你负责一波攻坚，TA 负责穿插补位。": "You attack in one wave; they fill in the gaps.",
            "你负责稳定巡航，TA 负责制造峰值。": "You cruise steadily; they create the peaks.",
            "你负责保持手感，TA 负责拉开节奏。": "You keep the habit warm; they set the tempo.",
            "让 TokenFleet 按你的节奏记录 Token 消耗": "Let TokenFleet track token usage at your rhythm",
            "语言": "Language",
            "选择 TokenFleet 的显示语言": "Choose how TokenFleet speaks to you",
            "当前语言": "Current language",
            "切换后立即生效": "Changes apply immediately",
            "TokenFleet · Local usage tracker": "TokenFleet · Local usage tracker",
            "每日目标": "Daily Goal",
            "token / 天": "tokens / day",
            "自动刷新": "Auto Refresh",
            "显示入口": "Display Entry",
            "面板可见时按此频率检查；后台会根据供电状态降低频率。": "Visible panels check at this rhythm; background refresh slows down based on power state.",
            "手动更新": "Manual refresh",
            "每 %@": "Every %@",
            "当前节奏": "Current rhythm",
            "显示位置": "Display Position",
            "刘海屏显示在刘海旁，其他屏幕使用菜单栏。": "On notch displays, show beside the notch. Otherwise use the menu bar.",
            "主题色": "Theme Color",
            "菜单栏、圆环、活动墙和按钮会一起跟随主题变化。": "The menu bar, rings, activity wall, and buttons follow the theme.",
            "当前主题": "Current theme",
            "登录后自动启动 TokenFleet": "Launch TokenFleet at login",
            "请先把 TokenFleet 拖到 Applications 后再开启开机启动。": "Move TokenFleet to Applications before enabling launch at login.",
            "像步数一样默默记录，避免漏掉每天的 Token 消耗。": "Track quietly like steps, so daily token usage is not missed.",
            "自动更新": "Auto Update",
            "社群榜同步（可选）": "Community Leaderboard Sync (Optional)",
            "清除社群榜连接？": "Clear community leaderboard connection?",
            "取消": "Cancel",
            "清除连接": "Clear Connection",
            "将移除本机设备凭证与同步状态；本地 Token 统计不会删除。": "This removes the device credential and sync state. Local Token statistics stay intact.",
            "已连接社群榜服务器": "Connected to Community Leaderboard Server",
            "立即同步": "Sync Now",
            "打开排行榜": "Open Leaderboard",
            "打开社群榜": "Open Community Leaderboard",
            "从专属接入页复制一次性注册码，粘贴后确认；注册码仅用于本次注册。": "Copy the one-time enrollment code from your private connection page, paste it here, and confirm. The code is used only for this enrollment.",
            "一次性注册码": "One-time enrollment code",
            "连接中": "Connecting",
            "确认并开始同步": "Confirm & Start Sync",
            "确认后会立即上传当前可验证的历史日汇总，并持续在后台同步。": "After confirmation, current verifiable historical daily aggregates are uploaded immediately and background sync continues.",
            "已有连接不属于当前固定社群服务器，请使用新的一次性注册码重新连接。": "The existing connection does not belong to the fixed community server. Reconnect with a new one-time enrollment code.",
            "只同步日汇总": "Daily Aggregates Only",
            "连接后公开：昵称、Token、估算费用、工具、模型与日趋势": "Public after connecting: nickname, Tokens, estimated cost, tools, models, and daily trends",
            "仅上传日期、时区、工具、模型与 Token 数": "Uploads only date, timezone, tool, model, and Token counts",
            "不上传主机名、序列号、本地路径、提示词、代码或会话正文": "Never uploads hostname, serial number, local paths, prompts, code, or session content",
            "设备密钥只存 macOS 钥匙串": "Device secret stays in macOS Keychain",
            "与生财 OpenToken 的配置和凭证完全独立": "Completely separate from Shengcai OpenToken settings and credentials",
            "当前账务日固定为 Asia/Shanghai，上报时不做时区重组": "The accounting day is currently fixed to Asia/Shanghai and is uploaded without timezone regrouping",
            "需要重新连接": "Reconnect Required",
            "自动重试已停止": "Automatic Retry Stopped",
            "自动同步已开启": "Automatic Sync On",
            "自动同步已暂停": "Automatic Sync Paused",
            "尚未同步": "Not synced yet",
            "上次同步：%@": "Last sync: %@",
            "已跳过 %d 个无法安全同步的历史或分项桶": "Skipped %d historical or component buckets that could not be synced safely",
            "社群榜服务器地址必须是有效的 HTTPS 地址。": "The community leaderboard server must be a valid HTTPS URL.",
            "当前构建未配置有效的社群榜服务器，社群榜同步不可用。": "This build has no valid community leaderboard server configuration, so community sync is unavailable.",
            "请输入一次性注册码。": "Enter a one-time enrollment code.",
            "社群榜服务器返回了无效的注册信息。": "The community leaderboard server returned invalid enrollment data.",
            "社群榜服务器未确认完整接收本次日汇总，已停止自动重试。": "The community leaderboard server did not confirm the full daily aggregate batch, so automatic retries stopped.",
            "本地日汇总未通过同步校验。": "The local daily aggregate failed sync validation.",
            "请先连接社群榜服务器。": "Connect to a community leaderboard server first.",
            "设备凭证已失效，请清除后重新连接。": "The device credential is no longer valid. Clear it and reconnect.",
            "同步请求被拒绝，已停止自动重试；请检查服务器配置或更新客户端。": "The sync request was rejected and automatic retries stopped. Check the server configuration or update the client.",
            "无法从钥匙串读取设备凭证，请重新连接。": "The device credential could not be read from Keychain. Reconnect the device.",
            "无法保存社群榜同步状态。": "The community leaderboard sync state could not be saved.",
            "社群榜服务器暂时无法连接。": "The community leaderboard server is temporarily unavailable.",
            "社群榜服务器返回错误（%d）。": "The community leaderboard server returned an error (%d).",
            "无法访问钥匙串中的团队设备凭证。": "The team device credential could not be accessed in Keychain.",
            "当前构建未启用安全凭据存储，社群榜同步保持关闭。": "Secure credential storage is not enabled in this build, so community leaderboard sync remains off.",
            "自动检查 TokenFleet 新版本": "Check for TokenFleet updates automatically",
            "有更新时先提醒你，下载前会确认。": "You will be notified first, and asked before downloading.",
            "检查中": "Checking",
            "检查更新": "Check Updates",
            "隐私状态": "Privacy Status",
            "本地隐私保护已开启": "Local privacy protection is on",
            "代码与对话不会离开这台 Mac": "Code and chats never leave this Mac",
            "恢复默认": "Reset Defaults",
            "完成": "Done",
            "可更新": "Update available",
            "正在检查": "Checking",
            "尚未检查": "Not checked yet",
            "当前版本 %@": "Current version %@",
            "发现 %@": "Found %@",
            "下载前询问": "Ask before download",
            "仅安装已签名公证版本": "Only install signed and notarized builds",
            "开机启动": "Launch at Login",
            "已开启": "On",
            "已关闭": "Off",
            "下次登录会自动运行": "Runs automatically next login",
            "需要手动启动 App": "Start the app manually",
            "不读取代码与对话": "Does not read code or chats",
            "不默认上传数据": "Does not upload by default",
            "本机": "This Mac",
            "%d 个客户端": "%d clients",
            "截取设置页": "Capture settings",
            "复制设置截图": "Copy settings screenshot",
            "保存设置 PNG": "Save settings PNG",
            "今日 Token 消耗": "Daily Token Usage",
            "每日 Token 消耗追踪": "Daily Token Tracking",
            "Codex 剩余额度": "Codex Quota",
            "Agent 剩余额度": "Agent Quota",
            "Codex 额度显示": "Show Codex Quota",
            "Agent 额度显示": "Show Agent Quota",
            "Agent 消耗榜": "Agent Usage Rank",
            "Agent 消耗榜显示": "Show Agent Usage Rank",
            "显示": "Show",
            "隐藏": "Hide",
            "自动检测": "Auto Detect",
            "已自动显示": "Shown automatically",
            "已显示": "Shown",
            "已手动隐藏": "Hidden manually",
            "未检测到 Token Rank": "Token Rank not detected",
            "不读取身份与榜单": "No identity or rank access",
            "尚未关联": "Not linked",
            "已自动关联": "Automatically linked",
            "安装 Token Rank 后自动识别": "Detected after Token Rank is installed",
            "数据同步": "Data sync",
            "我的消耗": "My Usage",
            "打开榜单": "Open Rank",
            "全部工具": "All tools",
            "打开榜单页": "Open leaderboard",
            "打开个人页": "Open profile",
            "默认关闭": "Off by default",
            "不会请求榜单": "No rank request",
            "榜单地址不可用": "Leaderboard URL unavailable",
            "暂时无法读取榜单": "Leaderboard unavailable",
            "榜单同步失败，显示上次结果": "Sync failed, showing last result",
            "匿名用户": "Anonymous",
            "今日排名": "Today Rank",
            "今日排名 #%d": "Today rank #%d",
            "第 %d / %d · 超过 %d%% 参榜用户": "#%d of %d · Ahead of %d%%",
            "%d 人 · %@": "%d users · %@",
            "今日未上榜": "Not ranked today",
            "榜单暂不可用": "Leaderboard unavailable",
            "点击查看今日榜单": "View today’s leaderboard",
            "点击打开榜单页": "Open leaderboard",
            "今日榜首": "Top today",
            "今日榜单": "Today board",
            "我的今日 Token": "My Today Tokens",
            "全榜今日 Token": "All Today Tokens",
            "主力": "Main",
            "榜单": "Board",
            "上榜：": "Ranked:",
            "实验 Agent 来源": "Experimental Agent Sources",
            "启用 ZCode / Hermes": "Enable ZCode / Hermes",
            "启用 ZCode / Hermes / WorkBuddy": "Enable ZCode / Hermes / WorkBuddy",
            "只读取本地 usage 字段，不读取对话正文。": "Only reads local usage fields, never message content.",
            "已计入实验统计": "Included as experimental",
            "已发现，暂不可统计": "Found, not countable yet",
            "刷新中": "Refreshing",
            "等待刷新": "Waiting for refresh",
            "未发现数据源": "No data source found",
            "暂无可用 usage": "No usable usage yet",
            "结构待适配": "Schema needs support",
            "无法读取": "Unreadable",
            "Agent 工作强度": "Agent Work Intensity",
            "近 7 日均": "7-day avg",
            "打开今日页": "Open Today",
            "Agent Token": "Agent Tokens",
            "5 小时": "5 hours",
            "7 天": "7 days",
            "剩余 %@": "%@ left",
            "等待重置": "Reset pending",
            "即将重置": "Resetting soon",
            "%d 分后重置": "Resets in %d min",
            "约 %d:%02d 后重置": "Resets in about %d:%02d",
            "%d 天后重置": "Resets in %d days",
            "刚刚": "Just now",
            "%d 分钟前": "%d min ago",
            "%d 小时前": "%d hr ago",
            "暂未读取到 Codex 额度": "Codex quota unavailable",
            "暂未读取到 Claude Code 额度": "Claude Code quota unavailable",
            "暂未读取到 Agent 额度": "Agent quota unavailable",
            "打开并登录 Codex 后会自动显示额度。": "Open and sign in to Codex to show quota automatically.",
            "打开并登录 Codex / Claude Code 后会自动显示。": "Open and sign in to Codex / Claude Code to show quota automatically.",
            "复制浮层截图": "Copy popover screenshot",
            "保存浮层 PNG": "Save popover PNG",
            "截取浮层": "Capture popover",
            "细线是每日目标": "Thin line marks the daily goal",
            "手动刷新": "Manual refresh",
            "刷新 %@": "Refresh %@",
            "打开仪表盘": "Open Dashboard",
            "退出": "Quit",
            "青绿": "Green",
            "海蓝": "Ocean",
            "紫藤": "Violet",
            "琥珀": "Amber",
            "石墨": "Graphite",
            "默认": "Default",
            "清爽": "Fresh",
            "温暖": "Warm",
            "专注": "Focus",
            "发现新版本 %@": "New version %@ available",
            "内存占用优化与稳定性改进": "Memory and stability improvements",
            "立即更新": "Update Now",
            "稍后": "Later",
            "TokenFleet %@ 可用": "TokenFleet %@ Available",
            "安装完成后会自动重启到新版本": "TokenFleet will relaunch after installation",
            "更新内容": "What’s New",
            "自动安装到 Applications": "Install to Applications",
            "下载后会验证 DMG 中的 App，并替换旧版本": "After download, the app in the DMG is verified and replaces the old version",
            "跳过此版本": "Skip Version",
            "安装中": "Installing",
            "安装并重启": "Install & Relaunch",
            "优化 Codex 历史数据读取": "Improved Codex history reading",
            "降低后台刷新 CPU 占用": "Reduced background refresh CPU usage",
            "提升菜单栏同步稳定性": "Improved menu bar sync stability",
            "当前版本未配置 TokenFleet 更新服务，已停止检查更新。": "TokenFleet update service is not configured in this build, so update checks are disabled.",
            "检查更新失败，请稍后再试。": "Could not check for updates. Please try again later.",
            "新版本没有可下载的 DMG。": "The new version has no downloadable DMG.",
            "下载更新失败，请稍后再试。": "Could not download the update. Please try again later.",
            "新版本未通过签名或公证验证，已停止安装。": "The new version did not pass signing or notarization checks.",
            "自动安装失败，请稍后重试，或手动把 TokenFleet 拖到 Applications。": "Automatic install failed. Try again later, or drag TokenFleet to Applications manually.",
            "只统计 token 数量": "Only counts token usage",
            "用于计算今日 Token 消耗、历史趋势和消耗金额。": "Used for daily token usage, trends, and estimated cost.",
            "所有数据文件都保留在这台 Mac 上。": "All data files stay on this Mac.",
            "消耗金额仅供参考": "Cost is only an estimate",
            "按本地价格表粗略估算，不等于真实账单。": "Estimated locally and may not match your real bill.",
            "本地优先": "Local First",
            "本地文件": "Local Files",
            "用量数据": "Usage data",
            "只有主动连接社群榜后才同步日汇总；代码、提示词和会话正文始终留在本机。": "Daily aggregates sync only after you explicitly connect the community leaderboard; code, prompts, and session content always stay on this Mac.",
            "加入社群榜需要单独连接和确认；未连接时不会上传日汇总。": "Joining the community leaderboard requires a separate connection and confirmation; no daily aggregates are uploaded while disconnected.",
            "截图": "Screenshot",
            "复制截图": "Copy screenshot",
            "保存 PNG": "Save PNG",
            "TokenFleet 更新": "TokenFleet Update",
            "未检测到可用屏幕": "No available display detected",
            "当前主屏无刘海，已回到菜单栏": "The main display has no notch, so TokenFleet is using the menu bar",
            "截图生成失败，请稍后再试。": "Could not create the screenshot. Please try again later.",
            "PNG 文件生成失败，请稍后再试。": "Could not create the PNG file. Please try again later.",
            "JPG 文件生成失败，请稍后再试。": "Could not create the JPG file. Please try again later.",
            "采集脚本退出码 %d": "Collector exited with code %d",
            "采集脚本退出码 %d：%@": "Collector exited with code %d: %@",
            "切换到%@主题": "Switch to %@ theme",
            "TokenFleet 自动更新失败": "TokenFleet Auto Update Failed",
            "请手动把 DMG 里的 TokenFleet 拖到 Applications。": "Please drag TokenFleet from the DMG into Applications manually.",
        ],
        .zhHant: [
            "简体中文": "簡體中文",
            "自动": "自動",
            "刘海左侧": "瀏海左側",
            "刘海右侧": "瀏海右側",
            "菜单栏": "選單列",
            "左侧": "左側",
            "右侧": "右側",
            "跟随系统": "跟隨系統",
            "自动匹配 macOS": "自動匹配 macOS",
            "准备更新": "準備更新",
            "正在下载": "正在下載",
            "正在安装并重启": "正在安裝並重新啟動",
            "更新失败": "更新失敗",
            "菜单栏模式": "選單列模式",
            "自动：刘海旁": "自動：瀏海旁",
            "自动：菜单栏": "自動：選單列",
            "鼠标移入后展开浮层": "滑鼠移入後展開浮層",
            "仅使用右上角菜单栏入口": "僅使用右上角選單列入口",
            "刷新": "重新整理",
            "打开 TokenFleet": "開啟 TokenFleet",
            "设置": "設定",
            "等待同步": "等待同步",
            "Token 采集超时，请稍后重试": "Token 採集逾時，請稍後重試",
            "Token 重新校准未完成，已保留原统计。": "Token 重新校準未完成，已保留原統計。",
            "TokenFleet 已按真实增量重新校准历史 Token。数字可能变小，但历史记录没有丢失。": "TokenFleet 已按真實增量重新校準歷史 Token。數字可能變小，但歷史記錄沒有遺失。",
            "关闭": "關閉",
            "手动": "手動",
            "%d 分钟": "%d 分鐘",
            "1 分钟": "1 分鐘",
            "第 %d 圈": "第 %d 圈",
            "第 %d 圈 · %@": "第 %d 圈 · %@",
            "已完成 %d 圈": "已完成 %d 圈",
            "已完成 %@": "已完成 %@",
            "每圈目标 %@": "每圈目標 %@",
            "少": "少",
            "多": "多",
            "活跃": "活躍",
            "达标": "達標",
            "最高": "最高",
            "近 8 个月活动墙": "近 8 個月活動牆",
            "颜色越深，越接近或超过每日目标": "顏色越深，越接近或超過每日目標",
            "颜色越深，用量越高；描边是今天": "顏色越深，用量越高；描邊是今天",
            "%d 个活跃日": "%d 個活躍日",
            "全部明细": "全部明細",
            "%d 条记录，向下滚动查看完整历史": "%d 條記錄，向下捲動查看完整歷史",
            "最近 %d 天，适合保存为截图": "最近 %d 天，適合儲存為截圖",
            "日期": "日期",
            "Token 消耗": "Token 消耗",
            "消耗金额": "消耗金額",
            "主力工具": "主力工具",
            "工具": "工具",
            "%d 个模型": "%d 個模型",
            "输入": "輸入",
            "输出": "輸出",
            "缓存读": "快取讀取",
            "缓存写": "快取寫入",
            "总计": "總計",
            "工具汇总": "工具彙總",
            "模型汇总": "模型彙總",
            "无可用汇总": "沒有可用彙總",
            "仅总量 · 分项不完整": "僅總量 · 分項不完整",
            "旧数据仅有工具与模型的独立汇总，无法还原它们的对应关系。": "舊資料只有工具與模型的獨立彙總，無法還原它們的對應關係。",
            "原子明细与当日总计不一致，本次仅展示已采集的精确明细。": "原子明細與當日總計不一致，本次僅顯示已採集的精確明細。",
            "无": "無",
            "累计 Token 消耗": "累計 Token 消耗",
            "等待下一次同步": "等待下一次同步",
            "最近 30 天": "最近 30 天",
            "颜色越深，圈数越高": "顏色越深，圈數越高",
            "柱越高，用量越多；颜色代表客户端": "柱越高，用量越多；顏色代表客戶端",
            "柱越高，用量越多": "柱越高，用量越多",
            "颜色代表客户端": "顏色代表客戶端",
            "今天 %@": "今天 %@",
            "/ %@ 每圈": "/ %@ 每圈",
            "圈数进度": "圈數進度",
            "按客户端": "按客戶端",
            "按模型": "按模型",
            "今日客户端": "今日客戶端",
            "今日模型": "今日模型",
            "累计总量分布": "累計總量分布",
            "主力模型": "主力模型",
            "本月均值": "本月均值",
            "活跃天数": "活躍天數",
            "达标天数": "達標天數",
            "有 AI 使用的日期": "有 AI 使用的日期",
            "达到每日目标": "達到每日目標",
            "%d圈完成": "%d圈完成",
            "%@进行中": "%@進行中",
            "所有本机记录": "所有本機記錄",
            "今日": "今日",
            "历史": "歷史",
            "统计": "統計",
            "模型与工具": "模型與工具",
            "隐私": "隱私",
            "今日消耗": "今日消耗",
            "历史活动": "歷史活動",
            "用量统计": "用量統計",
            "今天的 Token 使用节奏": "今天的 Token 使用節奏",
            "长期节奏和所有历史记录": "長期節奏和所有歷史記錄",
            "按客户端和模型拆开看": "按客戶端和模型拆開看",
            "只统计数量，不读取内容": "只統計數量，不讀取內容",
            "保存当前页 PNG（最近 30 天）": "儲存目前頁 PNG（最近 30 天）",
            "保存当前页 PNG": "儲存目前頁 PNG",
            "复制当前页截图": "複製目前頁截圖",
            "截取当前页": "擷取目前頁",
            "更新": "更新",
            "同步中": "同步中",
            "已同步": "已同步",
            "每天一个亿": "每天一個億",
            "本地统计": "本地統計",
            "本地统计 + 社群榜日汇总": "本地統計 + 社群榜每日彙總",
            "不上传代码或对话": "不上傳程式碼或對話",
            "今日 AI 战绩": "今日 AI 戰績",
            "昨日 AI 工作成绩单": "昨日 AI 工作成績單",
            "今天我和 AI 一起消耗了": "今天我和 AI 一起消耗了",
            "昨天我和 AI 一起完成了": "昨天我和 AI 一起完成了",
            "已完成": "已完成",
            "仅供参考": "僅供參考",
            "今日来源": "今日來源",
            "昨日来源": "昨日來源",
            "今日 Token": "今日 Token",
            "按 Token 消耗排序": "按 Token 消耗排序",
            "完成度": "完成度",
            "总完成度": "總完成度",
            "这是一个新的记录日": "這是一個新的記錄日",
            "和前一天基本持平": "和前一天基本持平",
            "比前一天多 %@": "比前一天多 %@",
            "比前一天少 %@": "比前一天少 %@",
            "分享今日卡片": "分享今日卡片",
            "分享昨日成绩": "分享昨日成績",
            "分享昨日节奏": "分享昨日節奏",
            "下载今日卡片": "下載今日卡片",
            "下载昨日成绩": "下載昨日成績",
            "下载昨日节奏": "下載昨日節奏",
            "分享战绩卡片": "分享戰績卡片",
            "截图与分享": "截圖與分享",
            "还没有昨日数据": "還沒有昨日資料",
            "昨日节奏还在等待同步": "昨日節奏還在等待同步",
            "本地 AI 使用节奏": "本地 AI 使用節奏",
            "AI Token 使用追踪": "AI Token 使用追蹤",
            "昨日 AI 节奏": "昨日 AI 節奏",
            "完整 24h": "完整 24h",
            "24 小时波形": "24 小時波形",
            "颜色随时段变化，最高柱是峰值": "顏色隨時段變化，最高柱是峰值",
            "峰值": "峰值",
            "峰值 %@": "峰值 %@",
            "活跃时段": "活躍時段",
            "%d 个时段": "%d 個時段",
            "昨日 Token": "昨日 Token",
            "夜间占比": "夜間占比",
            "最长连续": "最長連續",
            "%d 小时": "%d 小時",
            "全天总量": "全天總量",
            "昨天的完整 AI 协作节拍": "昨天的完整 AI 協作節拍",
            "清晨启动型": "清晨啟動型",
            "上午规划型": "上午規劃型",
            "下午爆发型": "下午爆發型",
            "晚间冲刺型": "晚間衝刺型",
            "夜间 Agent 型": "夜間 Agent 型",
            "双峰推进型": "雙峰推進型",
            "碎片推进型": "碎片推進型",
            "一波流型": "一波流型",
            "稳定巡航型": "穩定巡航型",
            "低频轻触型": "低頻輕觸型",
            "一早就把 AI 拉进工作台": "一早就把 AI 拉進工作台",
            "上午定方向，后面稳稳推进": "上午定方向，後面穩穩推進",
            "午后能量拉满，一段时间集中爆发": "午後能量拉滿，一段時間集中爆發",
            "晚间突然加速，把任务向前顶了一截": "晚間突然加速，把任務向前頂了一截",
            "夜里交给 Agent，把任务往前推": "夜裡交給 Agent，把任務往前推",
            "一天两次拉满，节奏很有层次": "一天兩次拉滿，節奏很有層次",
            "多时段穿插推进，随手就把活干了": "多時段穿插推進，隨手就把活幹了",
            "集中一波解决主要战斗": "集中一波解決主要戰鬥",
            "稳定巡航，没有明显掉线": "穩定巡航，沒有明顯掉線",
            "轻量使用，保留一点 AI 手感": "輕量使用，保留一點 AI 手感",
            "投缘搭子：夜间 Agent 型": "投緣搭子：夜間 Agent 型",
            "投缘搭子：下午爆发型": "投緣搭子：下午爆發型",
            "投缘搭子：上午规划型": "投緣搭子：上午規劃型",
            "投缘搭子：清晨启动型": "投緣搭子：清晨啟動型",
            "投缘搭子：稳定巡航型": "投緣搭子：穩定巡航型",
            "投缘搭子：一波流型": "投緣搭子：一波流型",
            "投缘搭子：碎片推进型": "投緣搭子：碎片推進型",
            "投缘搭子：双峰推进型": "投緣搭子：雙峰推進型",
            "你负责清晨开局，TA 负责夜里收尾。": "你負責清晨開局，TA 負責夜裡收尾。",
            "你负责上午定盘，TA 负责下午冲刺。": "你負責上午定盤，TA 負責下午衝刺。",
            "你负责午后爆发，TA 负责上午定盘。": "你負責午後爆發，TA 負責上午定盤。",
            "你负责深夜推进，TA 负责清晨接棒。": "你負責深夜推進，TA 負責清晨接棒。",
            "你负责两次拉满，TA 负责稳定托底。": "你負責兩次拉滿，TA 負責穩定托底。",
            "你负责随手推进，TA 负责集中攻坚。": "你負責隨手推進，TA 負責集中攻堅。",
            "你负责一波攻坚，TA 负责穿插补位。": "你負責一波攻堅，TA 負責穿插補位。",
            "你负责稳定巡航，TA 负责制造峰值。": "你負責穩定巡航，TA 負責製造峰值。",
            "你负责保持手感，TA 负责拉开节奏。": "你負責保持手感，TA 負責拉開節奏。",
            "让 TokenFleet 按你的节奏记录 Token 消耗": "讓 TokenFleet 按你的節奏記錄 Token 消耗",
            "语言": "語言",
            "选择 TokenFleet 的显示语言": "選擇 TokenFleet 的顯示語言",
            "当前语言": "目前語言",
            "切换后立即生效": "切換後立即生效",
            "TokenFleet · Local usage tracker": "TokenFleet · 本地用量追蹤器",
            "每日目标": "每日目標",
            "token / 天": "token / 天",
            "自动刷新": "自動重新整理",
            "显示入口": "顯示入口",
            "面板可见时按此频率检查；后台会根据供电状态降低频率。": "面板可見時按此頻率檢查；背景會依供電狀態降低頻率。",
            "手动更新": "手動更新",
            "每 %@": "每 %@",
            "当前节奏": "目前節奏",
            "显示位置": "顯示位置",
            "刘海屏显示在刘海旁，其他屏幕使用菜单栏。": "瀏海螢幕顯示在瀏海旁，其他螢幕使用選單列。",
            "主题色": "主題色",
            "菜单栏、圆环、活动墙和按钮会一起跟随主题变化。": "選單列、圓環、活動牆和按鈕會一起跟隨主題變化。",
            "当前主题": "目前主題",
            "登录后自动启动 TokenFleet": "登入後自動啟動 TokenFleet",
            "请先把 TokenFleet 拖到 Applications 后再开启开机启动。": "請先把 TokenFleet 拖到 Applications 後再開啟開機啟動。",
            "像步数一样默默记录，避免漏掉每天的 Token 消耗。": "像步數一樣默默記錄，避免漏掉每天的 Token 消耗。",
            "自动更新": "自動更新",
            "社群榜同步（可选）": "社群榜同步（可選）",
            "清除社群榜连接？": "清除社群榜連線？",
            "取消": "取消",
            "清除连接": "清除連線",
            "将移除本机设备凭证与同步状态；本地 Token 统计不会删除。": "將移除本機裝置憑證與同步狀態；本地 Token 統計不會刪除。",
            "已连接社群榜服务器": "已連接社群榜伺服器",
            "立即同步": "立即同步",
            "打开排行榜": "開啟排行榜",
            "打开社群榜": "開啟社群榜",
            "从专属接入页复制一次性注册码，粘贴后确认；注册码仅用于本次注册。": "從專屬接入頁複製一次性註冊碼，貼上後確認；註冊碼僅用於本次註冊。",
            "一次性注册码": "一次性註冊碼",
            "连接中": "連線中",
            "确认并开始同步": "確認並開始同步",
            "确认后会立即上传当前可验证的历史日汇总，并持续在后台同步。": "確認後會立即上傳目前可驗證的歷史每日彙總，並持續在背景同步。",
            "已有连接不属于当前固定社群服务器，请使用新的一次性注册码重新连接。": "已有連線不屬於目前固定社群伺服器，請使用新的一次性註冊碼重新連線。",
            "只同步日汇总": "只同步每日彙總",
            "连接后公开：昵称、Token、估算费用、工具、模型与日趋势": "連接後公開：暱稱、Token、估算費用、工具、模型與每日趨勢",
            "仅上传日期、时区、工具、模型与 Token 数": "僅上傳日期、時區、工具、模型與 Token 數",
            "不上传主机名、序列号、本地路径、提示词、代码或会话正文": "不上傳主機名稱、序號、本地路徑、提示詞、程式碼或工作階段正文",
            "设备密钥只存 macOS 钥匙串": "裝置密鑰只存於 macOS 鑰匙圈",
            "与生财 OpenToken 的配置和凭证完全独立": "與生財 OpenToken 的設定和憑證完全獨立",
            "当前账务日固定为 Asia/Shanghai，上报时不做时区重组": "目前帳務日固定為 Asia/Shanghai，上報時不進行時區重組",
            "需要重新连接": "需要重新連線",
            "自动重试已停止": "自動重試已停止",
            "自动同步已开启": "自動同步已開啟",
            "自动同步已暂停": "自動同步已暫停",
            "尚未同步": "尚未同步",
            "上次同步：%@": "上次同步：%@",
            "已跳过 %d 个无法安全同步的历史或分项桶": "已略過 %d 個無法安全同步的歷史或分項桶",
            "社群榜服务器地址必须是有效的 HTTPS 地址。": "社群榜伺服器位址必須是有效的 HTTPS 位址。",
            "当前构建未配置有效的社群榜服务器，社群榜同步不可用。": "目前版本未設定有效的社群榜伺服器，因此社群榜同步不可用。",
            "请输入一次性注册码。": "請輸入一次性註冊碼。",
            "社群榜服务器返回了无效的注册信息。": "社群榜伺服器回傳了無效的註冊資訊。",
            "社群榜服务器未确认完整接收本次日汇总，已停止自动重试。": "社群榜伺服器未確認完整接收本次每日彙總，已停止自動重試。",
            "本地日汇总未通过同步校验。": "本地每日彙總未通過同步驗證。",
            "请先连接社群榜服务器。": "請先連接社群榜伺服器。",
            "设备凭证已失效，请清除后重新连接。": "裝置憑證已失效，請清除後重新連線。",
            "同步请求被拒绝，已停止自动重试；请检查服务器配置或更新客户端。": "同步請求遭拒，已停止自動重試；請檢查伺服器設定或更新客戶端。",
            "无法从钥匙串读取设备凭证，请重新连接。": "無法從鑰匙圈讀取裝置憑證，請重新連線。",
            "无法保存社群榜同步状态。": "無法儲存社群榜同步狀態。",
            "社群榜服务器暂时无法连接。": "社群榜伺服器暫時無法連線。",
            "社群榜服务器返回错误（%d）。": "社群榜伺服器回傳錯誤（%d）。",
            "无法访问钥匙串中的团队设备凭证。": "無法存取鑰匙圈中的團隊裝置憑證。",
            "当前构建未启用安全凭据存储，社群榜同步保持关闭。": "目前版本未啟用安全憑據儲存，因此社群榜同步維持關閉。",
            "自动检查 TokenFleet 新版本": "自動檢查 TokenFleet 新版本",
            "有更新时先提醒你，下载前会确认。": "有更新時先提醒你，下載前會確認。",
            "检查中": "檢查中",
            "检查更新": "檢查更新",
            "隐私状态": "隱私狀態",
            "本地隐私保护已开启": "本地隱私保護已開啟",
            "代码与对话不会离开这台 Mac": "程式碼與對話不會離開這台 Mac",
            "恢复默认": "恢復預設",
            "完成": "完成",
            "可更新": "可更新",
            "正在检查": "正在檢查",
            "尚未检查": "尚未檢查",
            "当前版本 %@": "目前版本 %@",
            "发现 %@": "發現 %@",
            "下载前询问": "下載前詢問",
            "仅安装已签名公证版本": "僅安裝已簽名公證版本",
            "开机启动": "開機啟動",
            "已开启": "已開啟",
            "已关闭": "已關閉",
            "下次登录会自动运行": "下次登入會自動執行",
            "需要手动启动 App": "需要手動啟動 App",
            "不读取代码与对话": "不讀取程式碼與對話",
            "不默认上传数据": "不預設上傳資料",
            "本机": "本機",
            "%d 个客户端": "%d 個客戶端",
            "截取设置页": "擷取設定頁",
            "复制设置截图": "複製設定截圖",
            "保存设置 PNG": "儲存設定 PNG",
            "今日 Token 消耗": "今日 Token 消耗",
            "每日 Token 消耗追踪": "每日 Token 消耗追蹤",
            "Codex 剩余额度": "Codex 剩餘額度",
            "Agent 剩余额度": "Agent 剩餘額度",
            "Codex 额度显示": "顯示 Codex 額度",
            "Agent 额度显示": "顯示 Agent 額度",
            "Agent 消耗榜": "Agent 消耗榜",
            "Agent 消耗榜显示": "顯示 Agent 消耗榜",
            "显示": "顯示",
            "隐藏": "隱藏",
            "自动检测": "自動偵測",
            "已自动显示": "已自動顯示",
            "已显示": "已顯示",
            "已手动隐藏": "已手動隱藏",
            "未检测到 Token Rank": "未偵測到 Token Rank",
            "不读取身份与榜单": "不讀取身分與榜單",
            "尚未关联": "尚未關聯",
            "已自动关联": "已自動關聯",
            "安装 Token Rank 后自动识别": "安裝 Token Rank 後自動識別",
            "数据同步": "資料同步",
            "我的消耗": "我的消耗",
            "打开榜单": "開啟榜單",
            "全部工具": "全部工具",
            "打开榜单页": "開啟榜單頁",
            "打开个人页": "開啟個人頁",
            "默认关闭": "預設關閉",
            "不会请求榜单": "不會請求榜單",
            "榜单地址不可用": "榜單地址不可用",
            "暂时无法读取榜单": "暫時無法讀取榜單",
            "榜单同步失败，显示上次结果": "榜單同步失敗，顯示上次結果",
            "匿名用户": "匿名使用者",
            "今日排名": "今日排名",
            "今日排名 #%d": "今日排名 #%d",
            "第 %d / %d · 超过 %d%% 参榜用户": "第 %d / %d · 超過 %d%% 參榜使用者",
            "%d 人 · %@": "%d 人 · %@",
            "今日未上榜": "今日未上榜",
            "榜单暂不可用": "榜單暫不可用",
            "点击查看今日榜单": "點擊查看今日榜單",
            "点击打开榜单页": "點擊開啟榜單頁",
            "今日榜首": "今日榜首",
            "今日榜单": "今日榜單",
            "我的今日 Token": "我的今日 Token",
            "全榜今日 Token": "全榜今日 Token",
            "主力": "主力",
            "榜单": "榜單",
            "上榜：": "上榜：",
            "实验 Agent 来源": "實驗 Agent 來源",
            "启用 ZCode / Hermes": "啟用 ZCode / Hermes",
            "启用 ZCode / Hermes / WorkBuddy": "啟用 ZCode / Hermes / WorkBuddy",
            "只读取本地 usage 字段，不读取对话正文。": "只讀取本地 usage 欄位，不讀取對話正文。",
            "已计入实验统计": "已計入實驗統計",
            "已发现，暂不可统计": "已發現，暫不可統計",
            "刷新中": "刷新中",
            "等待刷新": "等待刷新",
            "未发现数据源": "未發現資料來源",
            "暂无可用 usage": "暫無可用 usage",
            "结构待适配": "結構待適配",
            "无法读取": "無法讀取",
            "Agent 工作强度": "Agent 工作強度",
            "近 7 日均": "近 7 日均",
            "打开今日页": "開啟今日頁",
            "Agent Token": "Agent Token",
            "5 小时": "5 小時",
            "7 天": "7 天",
            "剩余 %@": "剩餘 %@",
            "等待重置": "等待重置",
            "即将重置": "即將重置",
            "%d 分后重置": "%d 分後重置",
            "约 %d:%02d 后重置": "約 %d:%02d 後重置",
            "%d 天后重置": "%d 天後重置",
            "刚刚": "剛剛",
            "%d 分钟前": "%d 分鐘前",
            "%d 小时前": "%d 小時前",
            "暂未读取到 Codex 额度": "暫未讀取到 Codex 額度",
            "暂未读取到 Claude Code 额度": "暫未讀取到 Claude Code 額度",
            "暂未读取到 Agent 额度": "暫未讀取到 Agent 額度",
            "打开并登录 Codex 后会自动显示额度。": "開啟並登入 Codex 後會自動顯示額度。",
            "打开并登录 Codex / Claude Code 后会自动显示。": "開啟並登入 Codex / Claude Code 後會自動顯示。",
            "复制浮层截图": "複製浮層截圖",
            "保存浮层 PNG": "儲存浮層 PNG",
            "截取浮层": "擷取浮層",
            "细线是每日目标": "細線是每日目標",
            "手动刷新": "手動重新整理",
            "刷新 %@": "重新整理 %@",
            "打开仪表盘": "開啟儀表板",
            "退出": "退出",
            "青绿": "青綠",
            "海蓝": "海藍",
            "紫藤": "紫藤",
            "琥珀": "琥珀",
            "石墨": "石墨",
            "默认": "預設",
            "清爽": "清爽",
            "温暖": "溫暖",
            "专注": "專注",
            "发现新版本 %@": "發現新版本 %@",
            "内存占用优化与稳定性改进": "記憶體佔用最佳化與穩定性改進",
            "立即更新": "立即更新",
            "稍后": "稍後",
            "TokenFleet %@ 可用": "TokenFleet %@ 可用",
            "安装完成后会自动重启到新版本": "安裝完成後會自動重新啟動到新版本",
            "更新内容": "更新內容",
            "自动安装到 Applications": "自動安裝到 Applications",
            "下载后会验证 DMG 中的 App，并替换旧版本": "下載後會驗證 DMG 中的 App，並替換舊版本",
            "跳过此版本": "略過此版本",
            "安装中": "安裝中",
            "安装并重启": "安裝並重新啟動",
            "优化 Codex 历史数据读取": "最佳化 Codex 歷史資料讀取",
            "降低后台刷新 CPU 占用": "降低背景重新整理 CPU 佔用",
            "提升菜单栏同步稳定性": "提升選單列同步穩定性",
            "当前版本未配置 TokenFleet 更新服务，已停止检查更新。": "目前版本未設定 TokenFleet 更新服務，已停止檢查更新。",
            "检查更新失败，请稍后再试。": "檢查更新失敗，請稍後再試。",
            "新版本没有可下载的 DMG。": "新版本沒有可下載的 DMG。",
            "下载更新失败，请稍后再试。": "下載更新失敗，請稍後再試。",
            "新版本未通过签名或公证验证，已停止安装。": "新版本未通過簽名或公證驗證，已停止安裝。",
            "自动安装失败，请稍后重试，或手动把 TokenFleet 拖到 Applications。": "自動安裝失敗，請稍後重試，或手動把 TokenFleet 拖到 Applications。",
            "只统计 token 数量": "只統計 token 數量",
            "用于计算今日 Token 消耗、历史趋势和消耗金额。": "用於計算今日 Token 消耗、歷史趨勢和消耗金額。",
            "所有数据文件都保留在这台 Mac 上。": "所有資料檔案都保留在這台 Mac 上。",
            "消耗金额仅供参考": "消耗金額僅供參考",
            "按本地价格表粗略估算，不等于真实账单。": "按本地價格表粗略估算，不等於真實帳單。",
            "本地优先": "本地優先",
            "本地文件": "本地檔案",
            "用量数据": "用量資料",
            "只有主动连接社群榜后才同步日汇总；代码、提示词和会话正文始终留在本机。": "只有主動連接社群榜後才同步每日彙總；程式碼、提示詞和工作階段正文始終留在本機。",
            "加入社群榜需要单独连接和确认；未连接时不会上传日汇总。": "加入社群榜需要單獨連接和確認；未連接時不會上傳每日彙總。",
            "截图": "截圖",
            "复制截图": "複製截圖",
            "保存 PNG": "儲存 PNG",
            "TokenFleet 更新": "TokenFleet 更新",
            "未检测到可用屏幕": "未偵測到可用螢幕",
            "当前主屏无刘海，已回到菜单栏": "目前主螢幕無瀏海，已回到選單列",
            "截图生成失败，请稍后再试。": "截圖產生失敗，請稍後再試。",
            "PNG 文件生成失败，请稍后再试。": "PNG 檔案產生失敗，請稍後再試。",
            "JPG 文件生成失败，请稍后再试。": "JPG 檔案產生失敗，請稍後再試。",
            "采集脚本退出码 %d": "採集腳本退出碼 %d",
            "采集脚本退出码 %d：%@": "採集腳本退出碼 %d：%@",
            "切换到%@主题": "切換到%@主題",
            "TokenFleet 自动更新失败": "TokenFleet 自動更新失敗",
            "请手动把 DMG 里的 TokenFleet 拖到 Applications。": "請手動把 DMG 裡的 TokenFleet 拖到 Applications。"
        ]
    ]
}

func L(_ key: String) -> String {
    TokenStepLocalization.text(key)
}

func LFormat(_ key: String, _ arguments: CVarArg...) -> String {
    TokenStepLocalization.format(key, arguments)
}
