"""initial team ledger

Revision ID: 317c7501d905
Revises:
Create Date: 2026-08-09 11:07:37.139104
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '317c7501d905'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('default_timezone', sa.String(length=64), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('ledger_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('retention_days BETWEEN 30 AND 3650', name='ck_org_retention_days'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', name='userrole', native_enum=False, length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'org_id', name='uq_user_id_org'),
    sa.UniqueConstraint('org_id', 'email', name='uq_user_org_email')
    )
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_public_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('app_version', sa.String(length=64), nullable=False),
    sa.Column('collector_version', sa.String(length=64), nullable=False),
    sa.Column('signing_key', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_successful_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'org_id'], ['users.id', 'users.org_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'user_id', 'org_id', name='uq_device_id_user_org'),
    sa.UniqueConstraint('org_id', 'device_public_id', name='uq_device_org_public_id')
    )
    op.create_index('ix_device_org_user', 'devices', ['org_id', 'user_id'], unique=False)
    op.create_table('enrollment_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id', 'org_id'], ['users.id', 'users.org_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'org_id'], ['users.id', 'users.org_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_enrollment_org_user', 'enrollment_tokens', ['org_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_enrollment_tokens_token_hash'), 'enrollment_tokens', ['token_hash'], unique=True)
    op.create_table('price_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('tool', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('input_per_million', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('output_per_million', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('cache_read_per_million', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('cache_write_per_million', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('cache_read_per_million >= 0', name='ck_price_cache_read_nonnegative'),
    sa.CheckConstraint('cache_write_per_million >= 0', name='ck_price_cache_write_nonnegative'),
    sa.CheckConstraint('input_per_million >= 0', name='ck_price_input_nonnegative'),
    sa.CheckConstraint('output_per_million >= 0', name='ck_price_output_nonnegative'),
    sa.ForeignKeyConstraint(['created_by_user_id', 'org_id'], ['users.id', 'users.org_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'org_id', name='uq_price_id_org'),
    sa.UniqueConstraint('org_id', 'tool', 'model', 'effective_from', name='uq_price_scope_effective')
    )
    op.create_index('ix_price_lookup', 'price_versions', ['org_id', 'tool', 'model', 'effective_from'], unique=False)
    op.create_table('daily_usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('tool', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('completeness', sa.String(length=32), nullable=False),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cache_read_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cache_write_tokens', sa.BigInteger(), nullable=False),
    sa.Column('report_schema_version', sa.Integer(), nullable=False),
    sa.Column('collector_version', sa.String(length=64), nullable=False),
    sa.Column('reported_generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_version_id', sa.String(length=36), nullable=True),
    sa.Column('cost_microunits', sa.BigInteger(), nullable=True),
    sa.Column('cost_currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("completeness IN ('exact', 'legacy_marginal', 'fallback_estimate')", name='ck_usage_completeness'),
    sa.CheckConstraint('cache_read_tokens >= 0', name='ck_usage_cache_read_nonnegative'),
    sa.CheckConstraint('cache_write_tokens >= 0', name='ck_usage_cache_write_nonnegative'),
    sa.CheckConstraint('input_tokens >= 0', name='ck_usage_input_nonnegative'),
    sa.CheckConstraint('output_tokens >= 0', name='ck_usage_output_nonnegative'),
    sa.ForeignKeyConstraint(['device_id', 'user_id', 'org_id'], ['devices.id', 'devices.user_id', 'devices.org_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['price_version_id', 'org_id'], ['price_versions.id', 'price_versions.org_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id', 'org_id'], ['users.id', 'users.org_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'user_id', 'device_id', 'usage_date', 'timezone', 'tool', 'model', 'source', name='uq_daily_usage_natural_key')
    )
    op.create_index('ix_usage_org_date', 'daily_usage', ['org_id', 'usage_date'], unique=False)
    op.create_index('ix_usage_org_device_date', 'daily_usage', ['org_id', 'device_id', 'usage_date'], unique=False)
    op.create_index('ix_usage_org_user_date', 'daily_usage', ['org_id', 'user_id', 'usage_date'], unique=False)
    op.create_table('device_nonces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('nonce', sa.String(length=128), nullable=False),
    sa.Column('request_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'nonce', name='uq_device_nonce')
    )
    op.create_index('ix_device_nonce_created', 'device_nonces', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_device_nonce_created', table_name='device_nonces')
    op.drop_table('device_nonces')
    op.drop_index('ix_usage_org_user_date', table_name='daily_usage')
    op.drop_index('ix_usage_org_device_date', table_name='daily_usage')
    op.drop_index('ix_usage_org_date', table_name='daily_usage')
    op.drop_table('daily_usage')
    op.drop_index('ix_price_lookup', table_name='price_versions')
    op.drop_table('price_versions')
    op.drop_index(op.f('ix_enrollment_tokens_token_hash'), table_name='enrollment_tokens')
    op.drop_index('ix_enrollment_org_user', table_name='enrollment_tokens')
    op.drop_table('enrollment_tokens')
    op.drop_index('ix_device_org_user', table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
